version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "Planner-AI-Lambda-Message-Handler"
s3_prefix = "Planner-AI-Lambda-Message-Handler"
region = "eu-central-1"
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
resolve_s3 = true
