AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Planner-AI-Lambda-Message-Handler-Serverless

Resources:
  AppLambda:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      ImageUri: 'applambda:latest'
      MemorySize: 1024
      Description: 'App lambda endpoint (see tags for more info).'
      Timeout: 60
      Architectures:
        - arm64
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./
      DockerTag: latest
